server:
  port: 7001
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eurekaserver7002.com:7002/eureka/
  instance:
    hostname: eurekaserver7001.com
spring:
  application:
    name: eurekaserver
