
server:
  port: 8082
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://javalei.com:3306/cloud?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: Payment-Server
mybatis:
  type-aliases-package:
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver7002.com:7002/eureka,http://eurekaserver7001.com:7001/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: Payment-Server8082
    prefer-ip-address: true